---
# tasks file for Nagios
- name: Install Nagios Core Requisites
  apt:
    name: 
     - Build-essential
     - apache2
     - php
     - openssh
     - perl
     - make
     - php-gd
     - libgd-dev
     - libapache2-mod-php
     - libperl-dev
     - libssl-dev
     - daemon
     - wget
     - apache2-utils
     - unzip
    state: latest
    update_cache: yes

- name: Add Group Nagios Core Document
  group: 
     name: nagcmd
     state: present

- name: Add user
  user:
     name: nagios
     grouo: nagcmd
